### ISSUE TITLE
是否有考虑开发QQ频道与服务器消息互通的功能？

### ISSUE THREAD

**Issue by mangocraft** [RegadPoleCN/PlumBot#24]
go-cqhttp支持QQ频道消息互动，但是当前PlumBot只能向群聊发送消息，以后是否有考虑兼容QQ频道呢？

**Comment by RegadPoleCN** [comment]
抱歉，对于频道的支持我无法实现，主要是由于我本人没有频道使用资格，所以我没办法对频道更进一步的了解
