### ISSUE TITLE
[BUG]白名单识别不正确

### ISSUE THREAD

**Issue by ZoruaFox** [RegadPoleCN/PlumBot#27]
如图，CQ码替换不完全导致白名单被误识别
<img width="424" alt="e94e220cf186db9bad7641be549153cd" src="https://github.com/RegadPoleCN/PlumBot/assets/96456728/3f1c4de8-9699-46e4-b9fc-5541fb44206f">
![image](https://github.com/RegadPoleCN/PlumBot/assets/96456728/a29953e0-2ba5-4be6-a513-fe2e1291397d)

**Comment by RegadPoleCN** [comment]
Done!

**Comment by RegadPoleCN** [comment]
修复未成功，等我有空再试试，不行的话我就not planned了

**Comment by ZoruaFox** [comment]
not&nbsp;planned🌿

Zorua
***@***.***

中国民用航空飞行学院






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月12日(周一) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RegadPoleCN/PlumBot] [BUG]白名单识别不正确 (Issue #27)




 
修复未成功，等我有空再试试，不行的话我就not planned了
 
&mdash;

**Comment by RegadPoleCN** [comment]
go-cqhttp消息逻辑不清楚，不会修复
