### ISSUE TITLE
Velocity3.3.0无法使用

### ISSUE THREAD

**Issue by TheCCMT** [RegadPoleCN/PlumBot#34]
使用的是Velocity3.3.0-SNAPSHOT Build#400 但报错，无法使用
猜测是插件接口更新的原因
日志:[latest.log](https://github.com/user-attachments/files/16052897/latest.log)

**Comment by Starrain08** [comment]
看起来你用的kook模式

> 使用的是Velocity3.3.0-SNAPSHOT Build#400 但报错，无法使用 猜测是插件接口更新的原因 日志:[latest.log](https://github.com/user-attachments/files/16052897/latest.log)

看起来你用的是kook模式，如果使用onebotv11，改为go-cqhttp模式，如果使用的是kook，配置文件有选项未配置
