### ISSUE TITLE
启动消息导致账号被封控

### ISSUE THREAD

**Issue by JackHanner** [RegadPoleCN/PlumBot#35]
启动每次都要说plumbot启动，一说我的号就被风控了。能不能关掉，或者改掉，比如这些bot，启动关键词

**Comment by JackHanner** [comment]
![image](https://github.com/RegadPoleCN/PlumBot/assets/64300121/2ff08a04-b638-4f7f-a2eb-7bf2292efad5)

**Comment by JackHanner** [comment]
之前用别的插件很久都没问题，但是不支持folia，换到你的插件就在启动消息这里废了

**Comment by Xiaoniu2333** [comment]
加Qsign了吗

**Comment by RegadPoleCN** [comment]
账号风控去检查一下自己的问题，功能开关目前不考虑
